# Generated by Django 6.0.1 on 2026-04-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('region', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=100)),
                ('superficie', models.FloatField(help_text='En kg/hectare')),
                ('prix_vente', models.FloatField(help_text='En FCFA')),
                ('cout_production', models.FloatField(help_text='En FCFA')),
                ('date_recolte', models.DateField()),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='blog.producteur')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
