# Generated by Django 6.0.1 on 2026-04-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_producteur_remove_products_category_recolte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolte',
            name='rendement',
            field=models.FloatField(default=0, help_text='En kg/hectare'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='superficie',
            field=models.FloatField(help_text='En hectares'),
        ),
    ]
