# Generated by Django 6.0.1 on 2026-04-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recolte_rendement_alter_recolte_superficie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_alerte', models.CharField(choices=[('info', 'ℹ️ Information'), ('warning', '⚠️ Attention'), ('danger', '🔴 Danger'), ('success', '✅ Succès')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
